name: Deploy

on:
    push:
      branches:
        - master
  
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Check
          uses: actions/checkout@v3

        - name: Install
          run: |
            pip install -r requirements.txt

        - name: Env
          run: |
            echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
            echo OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }} >> .env
            echo TELEGRAM_ACCESS_TOKEN=${{ secrets.TELEGRAM_ACCESS_TOKEN }} >> .env

        - name: Copy
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.PA_HOST }}
            username: ${{ secrets.PA_USERNAME }}
            password: ${{ secrets.PA_PASSWORD }}
            source: "."
            target: "/home/${{ secrets.PA_USERNAME }}/"
  
        - name: Run
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.PA_HOST }}
            username: ${{ secrets.PA_USERNAME }}
            password: ${{ secrets.PA_PASSWORD }}
            script: |
            curl -H "Authorization: Token ${PYTHONANYWHERE_API_TOKEN}" -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/always-on/restart/
