name: Deploy

on:
    push:
      branches:
        - master
  
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Check
          uses: actions/checkout@v3
  
        - name: Copy
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.PA_HOST }}
            username: LouisLiu
            password: Lxz200603
            source: "."
            target: "/home/${{ secrets.PA_USERNAME }}/"
  
        - name: Run
          uses: appleboy/ssh-action@master
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            TELEGRAM_ACCESS_TOKEN: ${{ secrets.TELEGRAM_ACCESS_TOKEN }}
          with:
            host: ${{ secrets.PA_HOST }}
            username: ${{ secrets.PA_USERNAME }}
            password: ${{ secrets.PA_PASSWORD }}
            script: |
              export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
              export OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }}
              export TELEGRAM_ACCESS_TOKEN=${{ secrets.TELEGRAM_ACCESS_TOKEN }}
              cd /home/${{ secrets.PA_USERNAME }}/
              # Optional: Install dependencies, if any
              pip install -r requirements.txt
              python3 bot.py
